LIBDIRS= -L/usr/X11R6/lib
LDLIBS = -lglut -lGL -lGLU -lX11 -lm

CPPFLAGS= -O3 -std=c++0x
LDFLAGS= $(CPPFLAGS) $(LIBDIRS)

TARGETS = tetris

SRCS = tetris.cpp tetromino.h cube.h cross_product.h

OBJS =  $(SRCS:.cpp=.o)

CXX = g++

default: $(TARGETS)
